apiVersion: v1
kind: Secret
metadata:
  name: askrag-secrets
  namespace: askrag-production
type: Opaque
stringData:
  # Application Secrets
  SECRET_KEY: "CHANGE_ME_PRODUCTION_SECRET_KEY_256_BITS"
  JWT_SECRET_KEY: "CHANGE_ME_JWT_SECRET_KEY_FOR_PRODUCTION"
  
  # Database
  MONGODB_URL: "mongodb://askrag_user:CHANGE_ME_PASSWORD@mongodb-service:27017/askrag_prod?authSource=askrag_prod"
  
  # OpenAI API
  OPENAI_API_KEY: "sk-CHANGE_ME_OPENAI_API_KEY_HERE"
  
  # Redis
  REDIS_URL: "redis://:CHANGE_ME_REDIS_PASSWORD@redis-service:6379"
  REDIS_PASSWORD: "CHANGE_ME_REDIS_PASSWORD"
  
  # CORS Origins
  CORS_ORIGINS: "https://askrag.yourdomain.com,https://api.askrag.yourdomain.com"
  
  # External Services
  SENTRY_DSN: "https://CHANGE_ME@sentry.io/project"
  DATADOG_API_KEY: "CHANGE_ME_DATADOG_API_KEY"
  
  # Email Configuration
  SMTP_USERNAME: "noreply@yourdomain.com"
  SMTP_PASSWORD: "CHANGE_ME_SMTP_PASSWORD"
  SMTP_SERVER: "smtp.yourdomain.com"
  FROM_EMAIL: "noreply@yourdomain.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: askrag-secrets
  namespace: askrag-staging
type: Opaque
stringData:
  # Application Secrets
  SECRET_KEY: "STAGING_SECRET_KEY_256_BITS_CHANGE_ME"
  JWT_SECRET_KEY: "STAGING_JWT_SECRET_KEY_CHANGE_ME"
  
  # Database
  MONGODB_URL: "mongodb://askrag_user:STAGING_PASSWORD@mongodb-service:27017/askrag_staging?authSource=askrag_staging"
  
  # OpenAI API
  OPENAI_API_KEY: "sk-STAGING_OPENAI_API_KEY_HERE"
  
  # Redis
  REDIS_URL: "redis://:STAGING_REDIS_PASSWORD@redis-service:6379"
  REDIS_PASSWORD: "STAGING_REDIS_PASSWORD"
  
  # CORS Origins
  CORS_ORIGINS: "https://staging-askrag.yourdomain.com,https://staging-api.yourdomain.com"
  
  # External Services
  SENTRY_DSN: "https://STAGING_SENTRY@sentry.io/project"
  DATADOG_API_KEY: "STAGING_DATADOG_API_KEY"
  
  # Email Configuration
  SMTP_USERNAME: "noreply-staging@yourdomain.com"
  SMTP_PASSWORD: "STAGING_SMTP_PASSWORD"
  SMTP_SERVER: "smtp.yourdomain.com"
  FROM_EMAIL: "noreply-staging@yourdomain.com"
